### ISSUE TITLE
LNK 2019

### ISSUE THREAD

**Issue by Frankenstein-bit** [tandasat/MemoryMon#7] opened 2020-09-11 08:20 UTC
when i compile the project, I always get the LNK ERROR,can you help me look at the error.
	
Severity	Code	Description	Project	File	Line	Suppression State
Warning	1324	[Version] section should specify PnpLockdown=1.	MemoryMon	C:\Users\Frankenstein\Desktop\tt\MemoryMon\MemoryMon\MemoryMon.inf	5	

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol _invoke_watson referenced in function "protected: virtual void __cdecl stdext::bad_alloc::_Doraise(void)const " (?_Doraise@bad_alloc@stdext@@MEBAXXZ)	MemoryMon	C:\Users\Frankenstein\Desktop\tt\MemoryMon\MemoryMon\AddressRanges.obj	1	

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol _invoke_watson	MemoryMon	C:\Users\Frankenstein\Desktop\tt\MemoryMon\MemoryMon\PageFaultRecord.obj	1	
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol _invoke_watson	MemoryMon	C:\Users\Frankenstein\Desktop\tt\MemoryMon\MemoryMon\V2PMap.obj	1	

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol "void (__cdecl* std::_Raise_handler)(class stdext::exception const &)" (?_Raise_handler@std@@3P6AXAEBVexception@stdext@@@ZEA)	MemoryMon	C:\Users\Frankenstein\Desktop\tt\MemoryMon\MemoryMon\AddressRanges.obj	1	

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol "void (__cdecl* std::_Raise_handler)(class stdext::exception const &)" (?_Raise_handler@std@@3P6AXAEBVexception@stdext@@@ZEA)	MemoryMon	C:\Users\Frankenstein\Desktop\tt\MemoryMon\MemoryMon\PageFaultRecord.obj	1	

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol "void (__cdecl* std::_Raise_handler)(class stdext::exception const &)" (?_Raise_handler@std@@3P6AXAEBVexception@stdext@@@ZEA)	MemoryMon	C:\Users\Frankenstein\Desktop\tt\MemoryMon\MemoryMon\V2PMap.obj	1	

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1120	2 unresolved externals	MemoryMon	C:\Users\Frankenstein\Desktop\tt\MemoryMon\x64\Debug\MemoryMon.sys	1

**Comment by tandasat** [comment] 2020-09-12 16:47
I am unable to reproduce the error using 16.7.3.

Try checking out and compiling the repo again.
`$ git clone --recursive https://github.com/tandasat/MemoryMon.git`

**Comment by Frankenstein-bit** [comment] 2020-09-14 02:26
> I am unable to reproduce the error using 16.7.3.
> Try checking out and compiling the repo again.
> $ git clone --recursive https://github.com/tandasat/MemoryMon.git

I use the git branch rwe_cdfs ,you may reproduce the problem by this branch. My vs is also 16.7.3

**Comment by tandasat** [comment] 2020-09-17 16:26
That is an unmaintained branch and I have no plan to maintain this, so closing this. 

However, you may try adding the code snippet posted here. It seems to be a similar issue.  
https://github.com/tandasat/DdiMon/issues/34

**Closed as completed by tandasat** 2020-09-17 16:26 UTC

**Comment by Frankenstein-bit** [comment] 2020-09-19 04:40
Thank you
